---
title: "Felidos de Costa Rica"
format: 
  dashboard:
    orientation: columns
---
```{r}
#| label: carga-paquetes

library(sf)
library(tidyverse)
library(DT)
library(plotly)
library(leaflet)
library(leaflet.extras)
library(leafem)
```

```{r}
#| label: carga-datos

felidos <-
  st_read(
    "felidos.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )

st_crs(felidos) <- 4326
```

# Mapa

## Column 

```{r}
#| label: mapa
#| title: "Distribución de registros de presencia"

leaflet() |>
  addTiles(group = "OSM") |>
  addProviderTiles(provider = providers$Esri.WorldImagery,
                   group = "Imágenes Satelitales"
                   ) |>
  addCircleMarkers(
    data = felidos,
    fillColor = "red",
    color = "red",
    radius = 4,
    group = "Félidos"
  ) |>
  addLayersControl(
    baseGroups = c("OSM", "Iamgenes Satelitales"),
    overlayGroups = ("Felidos")
  ) |>
  addResetMapButton() |>
  addSearchOSM() |> 
  addMouseCoordinates() |> 
  addScaleBar(
    position = "bottomleft", 
    options = scaleBarOptions(imperial = FALSE)
  ) |> 
  addMiniMap(position = "bottomright") |> 
  addFullscreenControl()  
```

# Tabla y Gráfico

## Column

```{r}
#| label: tabla}
#| title: "Lista de registros de presencia"

felidos |>
  st_drop_geometry() |>
  select(species, decimalLongitude, decimalLatitude, stateProvince) |>
  arrange(species) |>
  datatable(
    colnames = c("Especie", "Longitud", "Latitud", "Provincia"),
    rownames = FALSE
  )
```


```{r}
#| label: cantidad-registros-por-especie
#| title: "Cantidad de registros por especie"

grafico_ggplot2 <-
  felidos |>
  st_drop_geometry()|>
  group_by(species) |>
  summarize(n = n()) |>
  ggplot(aes(
    x = reorder(species, -n),
    y = n
  )) +
  geom_col()

ggplotly() |> config(locale = "es")
```
